---
- name: Configure Postfix and Dovecot
  hosts: localhost
  become: yes
  vars:
    domain_name: "172.31.32.169"
  tasks:
    - name: Configure Postfix main.cf
      template:
        src: postfix_main.cf.j2
        dest: /etc/postfix/main.cf
      notify: Restart Postfix

    - name: Configure Postfix master.cf
      template:
        src: postfix_master.cf.j2
        dest: /etc/postfix/master.cf
      notify: Restart Postfix

    - name: Configure Dovecot
      template:
        src: dovecot.conf.j2
        dest: /etc/dovecot/dovecot.conf
      notify: Restart Dovecot

  handlers:
    - name: Restart Postfix
      service:
        name: postfix
        state: restarted

    - name: Restart Dovecot
      service:
        name: dovecot
        state: restarted

